### PR TITLE
remove email requirement check

### PR DESCRIPTION
**Pull request by KevinBatdorf**
@DavidAnderson684 This just removes the email requirement before checking the server. This change doesn't break anything, but without it the changes on the server code wont be seen. So even if that branch is delayed, this on should be released.

### CODE REVIEW

**Comment by DavidAnderson684** [comment]
@KevinBatdorf I've made a release 1.7.0 with something slightly different. I've introduced a `set_require_login()` method. If you call that and set it to `false`, then it'll then disable that check. I thought it'd be best to just make this optional at first so that any problems any limited in scope (i.e. just to the plugin it's attempted in).

So, to use it, you'll need to add that call, and update `composer.json` to use 1.7.*; and update the code to use `Updraft_Manager_Updater_1_7`. (This has to be done on every new public method because if we stayed on 1.6 and added the new method, then the 1.6 class might be loaded from another plugin with the existing release without the method).

**Comment by KevinBatdorf** [comment]
@DavidAnderson684 I'm not sure this will work since all the logic is processed when it's initialized, right?

```php
$updater = new Updraft_Manager_Updater_1_7('http://metaslider.test', 1, 'ml-slider-pro/ml-slider-pro.php');
$updater->set_require_login(false); // Too late
```

Maybe it should be more like this?
```php
$require_login = !defined(UDMANAGER_ALLOW_NOT_LOGGED_IN) && (true != UDMANAGER_ALLOW_NOT_LOGGED_IN);
if (!$email && $require_login) return;
```

**Comment by DavidAnderson684** [comment]
@KevinBatdorf 

> since all the logic is processed when it's initialized, right?

Calling `set_require_login()`after the constructor will result in exactly the same execution flow as calling it within the constructor at the end.

**Comment by KevinBatdorf** [comment]
@DavidAnderson684 I don't think it will run because you call the main method directly from the constructor and not via a hook.

```php
public function __construct([...]) {
     ...
     $this->get_puc_updates_checker();
}
```
https://github.com/DavidAnderson684/simba-plugin-manager-updater/blob/master/class-udm-updater.php#L82

Maybe just add a filter?
```php
public function set_require_login($require_login) {
	$this->require_login = apply_filters('udmupdater_require_login', $require_login);
}
```

**Comment by DavidAnderson684** [comment]
@KevinBatdorf The code in our class where the email address is checked won't be called before you get back the class object.

**Comment by KevinBatdorf** [comment]
@DavidAnderson684 I didn't realize it does a check every 24 hours. But set up like this, it wont run on initial page load and instead has to wait for the first cycle 24 hours later. 

I don't see a problem with this, just different than what I expected initially would happen.

**Comment by KevinBatdorf** [comment]
@DavidAnderson684 Actually, it looks like the interval isn't set until it passes that test, so I'm not sure how it will run. Probably something I'm missing. 

I'll just test it now and report back.

**Comment by DavidAnderson684** [comment]
@KevinBatdorf There's no execution flow that can see the transient that the Yahnis class hooks into being requested (thus triggering the HTTP call) before the end of the constructor.

**Pull request closed without merging**
